chore: add pokt RPC endpoints
Badger-Finance/badger-rewards pull request #725
Opened 2022-03-09 20:55 UTC by mitche50

2022-03-09 21:24 UTC, btcookies requested changes

2022-03-09 21:24 UTC, btcookies commented on config/env_config.py
> +            self.make_provider("pokt/poly-node-url", "POLY_NODE_URL"),
should just be NODE_URL

2022-03-09 21:43 UTC, btcookies approved these changes
LGTM

2022-07-14 19:34 UTC, mitche50 commented
old pr, closing

2022-07-14 19:34 UTC, closed without merging